name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Criar arquivo .env no pipeline
        run: |
          echo "API_URL=${{ secrets.API_URL }}" >> .env
          echo "FRONT_URL=${{ secrets.FRONT_URL }}" >> .env

      - name: Rodar testes Cypress
        run: npm run test:run

      - name: Gerar relatório Mochawesome
        run: npm run test:report || true

      - name: Upload do relatório como artefato
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports/html

  deploy-report:
    needs: cypress-run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Baixar artefato do relatório
        uses: actions/download-artifact@v4
        with:
          name: cypress-report
          path: cypress-report

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress-report
          publish_branch: gh-pages
          force_orphan: true
